spring:
  application:
    name: gls-job-admin
  datasource:
    url: jdbc:mysql://172.31.124.62:3306/${spring.application.name}?serverTimezone=UTC&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mail:
    from: xxx@qq.com
    host: smtp.qq.com
    username: xxx@qq.com
    password: xxx
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
server:
  port: 8080
  servlet:
    context-path: /gls-job-admin
management:
  health:
    mail:
      enabled: false
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml
gls:
  job:
    accessToken: ''
    i18n: zh_CN
    logretentiondays: 30
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100