package com.gls.job.dashboard.web.entity.enums;

import com.gls.job.dashboard.core.constants.QuartzConstants;
import lombok.AllArgsConstructor;
import lombok.Getter;
import org.quartz.CalendarIntervalTrigger;
import org.quartz.CronTrigger;
import org.quartz.DailyTimeIntervalTrigger;
import org.quartz.SimpleTrigger;

/**
 * @author george
 */
@Getter
@AllArgsConstructor
public enum MisfireInstruction {

    /**
     * CalendarInterval
     */
    CALENDAR_INTERVAL_MISFIRE_INSTRUCTION_SMART_POLICY(QuartzConstants.TRIGGER_TYPE_CALENDAR_INTERVAL, CalendarIntervalTrigger.MISFIRE_INSTRUCTION_SMART_POLICY),
    CALENDAR_INTERVAL_MISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY(QuartzConstants.TRIGGER_TYPE_CALENDAR_INTERVAL, CalendarIntervalTrigger.MISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY),
    CALENDAR_INTERVAL_MISFIRE_INSTRUCTION_DO_NOTHING(QuartzConstants.TRIGGER_TYPE_CALENDAR_INTERVAL, CalendarIntervalTrigger.MISFIRE_INSTRUCTION_DO_NOTHING),
    CALENDAR_INTERVAL_MISFIRE_INSTRUCTION_FIRE_ONCE_NOW(QuartzConstants.TRIGGER_TYPE_CALENDAR_INTERVAL, CalendarIntervalTrigger.MISFIRE_INSTRUCTION_FIRE_ONCE_NOW),

    /**
     * Cron
     */
    CRON_MISFIRE_INSTRUCTION_SMART_POLICY(QuartzConstants.TRIGGER_TYPE_CRON, CronTrigger.MISFIRE_INSTRUCTION_SMART_POLICY),
    CRON_MISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY(QuartzConstants.TRIGGER_TYPE_CRON, CronTrigger.MISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY),
    CRON_MISFIRE_INSTRUCTION_DO_NOTHING(QuartzConstants.TRIGGER_TYPE_CRON, CronTrigger.MISFIRE_INSTRUCTION_DO_NOTHING),
    CRON_MISFIRE_INSTRUCTION_FIRE_ONCE_NOW(QuartzConstants.TRIGGER_TYPE_CRON, CronTrigger.MISFIRE_INSTRUCTION_FIRE_ONCE_NOW),

    /**
     * DailyTimeInterval
     */
    DAILY_TIME_INTERVAL_MISFIRE_INSTRUCTION_SMART_POLICY(QuartzConstants.TRIGGER_TYPE_DAILY_TIME_INTERVAL, DailyTimeIntervalTrigger.MISFIRE_INSTRUCTION_SMART_POLICY),
    DAILY_TIME_INTERVAL_MISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY(QuartzConstants.TRIGGER_TYPE_DAILY_TIME_INTERVAL, DailyTimeIntervalTrigger.MISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY),
    DAILY_TIME_INTERVAL_MISFIRE_INSTRUCTION_DO_NOTHING(QuartzConstants.TRIGGER_TYPE_DAILY_TIME_INTERVAL, DailyTimeIntervalTrigger.MISFIRE_INSTRUCTION_DO_NOTHING),
    DAILY_TIME_INTERVAL_MISFIRE_INSTRUCTION_FIRE_ONCE_NOW(QuartzConstants.TRIGGER_TYPE_DAILY_TIME_INTERVAL, DailyTimeIntervalTrigger.MISFIRE_INSTRUCTION_FIRE_ONCE_NOW),

    /**
     * Simple
     */
    SIMPLE_MISFIRE_INSTRUCTION_SMART_POLICY(QuartzConstants.TRIGGER_TYPE_SIMPLE, SimpleTrigger.MISFIRE_INSTRUCTION_SMART_POLICY),
    SIMPLE_MISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY(QuartzConstants.TRIGGER_TYPE_SIMPLE, SimpleTrigger.MISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY),
    SIMPLE_MISFIRE_INSTRUCTION_FIRE_NOW(QuartzConstants.TRIGGER_TYPE_SIMPLE, SimpleTrigger.MISFIRE_INSTRUCTION_FIRE_NOW),
    SIMPLE_MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_EXISTING_REPEAT_COUNT(QuartzConstants.TRIGGER_TYPE_SIMPLE, SimpleTrigger.MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_EXISTING_REPEAT_COUNT),
    SIMPLE_MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_REMAINING_REPEAT_COUNT(QuartzConstants.TRIGGER_TYPE_SIMPLE, SimpleTrigger.MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_REMAINING_REPEAT_COUNT),
    SIMPLE_MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_REMAINING_COUNT(QuartzConstants.TRIGGER_TYPE_SIMPLE, SimpleTrigger.MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_REMAINING_COUNT),
    SIMPLE_MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_EXISTING_COUNT(QuartzConstants.TRIGGER_TYPE_SIMPLE, SimpleTrigger.MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_EXISTING_COUNT),
    ;

    private final String type;
    private final int code;

}
